# Generated by Django 6.1 on 2026-08-19 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentskill',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='profiles.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='studentskill',
            constraint=models.UniqueConstraint(fields=('student_profile', 'skill'), name='unique_student_skill'),
        ),
    ]
