# Generated by Django 6.1 on 2026-08-19 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('internship_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='full_time', max_length=20)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='VNĐ', null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='VNĐ', null=True)),
                ('is_salary_negotiable', models.BooleanField(default=False)),
                ('experience_level', models.CharField(choices=[('no_experience', 'Không yêu cầu kinh nghiệm'), ('under_1_year', 'Dưới 1 năm'), ('1_year', '1 năm'), ('2_years_plus', 'Trên 2 năm')], default='no_experience', max_length=20)),
                ('min_academic_year', models.CharField(blank=True, choices=[('year_2', 'Năm 2'), ('year_3', 'Năm 3'), ('year_4', 'Năm 4'), ('graduated', 'Đã tốt nghiệp')], max_length=20)),
                ('num_positions', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối'), ('closed', 'Đã đóng'), ('expired', 'Hết hạn')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='profiles.employerprofile')),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='catalog.jobcategory')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='catalog.location')),
            ],
            options={
                'verbose_name_plural': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='catalog.skill')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobSkill', to='catalog.skill'),
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_views', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='profiles.studentprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobskill',
            constraint=models.UniqueConstraint(fields=('job', 'skill'), name='unique_job_skill'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'job_category', 'location'], name='jobs_job_status_efd025_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'is_featured'], name='jobs_job_status_510c04_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['deadline'], name='jobs_job_deadlin_c19edf_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job', 'viewed_at'], name='jobs_jobvie_job_id_d75b29_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedjob',
            constraint=models.UniqueConstraint(fields=('student_profile', 'job'), name='unique_saved_job'),
        ),
    ]
