# Generated by Django 6.1 on 2026-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('cv_snapshot', models.FileField(upload_to='cv_snapshots/')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('shortlisted', 'Đã chọn vào danh sách rút gọn'), ('interview_invited', 'Mời phỏng vấn'), ('accepted', 'Được nhận'), ('rejected', 'Bị từ chối'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('shortlisted', 'Đã chọn vào danh sách rút gọn'), ('interview_invited', 'Mời phỏng vấn'), ('accepted', 'Được nhận'), ('rejected', 'Bị từ chối'), ('cancelled', 'Đã hủy')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
