import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import client from "../../api/client";

export default function AdminDashboard() {
  const [stats, setStats] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { client.get("/admin/stats/").then(({ data }) => setStats(data)).catch(() => setError("Không thể tải số liệu quản trị.")); }, []);
  const cards = [["Người dùng", "users", "bi-people", "indigo", "/admin/users"], ["Tin tuyển dụng", "jobs", "bi-briefcase", "orange", "/admin/jobs"], ["Đơn ứng tuyển", "applications", "bi-file-earmark-text", "green", "/admin/applications"], ["Báo cáo chờ xử lý", "pending_reports", "bi-flag", "red", "/admin/reports"]];
  return <section className="admin-content"><div className="admin-welcome motion-in"><div><span className="eyebrow">OVERVIEW / 01</span><h2>Chào mừng trở lại.</h2><p>Theo dõi những chuyển động quan trọng của QLPM từ một nơi.</p></div><Link className="admin-primary" to="/admin/jobs"><i className="bi bi-plus-lg" /> Quản lý tin tuyển dụng</Link></div>{error && <div className="alert alert-warning motion-in">{error}</div>}<div className="admin-stats">{cards.map(([label, key, icon, color, to], index) => <Link className="stat-card motion-in" style={{ "--motion-delay": `${index * 70}ms` }} to={to} key={key}><span className={`stat-icon ${color}`}><i className={`bi ${icon}`} /></span><span className="stat-label">{label}</span><strong>{stats?.[key] ?? "—"}</strong><span className="stat-link">Xem chi tiết <i className="bi bi-arrow-up-right" /></span></Link>)}</div><div className="admin-panels"><article className="admin-panel motion-in" style={{ "--motion-delay": "280ms" }}><div className="panel-heading"><div><span className="eyebrow">HEALTH CHECK</span><h3>Trạng thái hệ thống</h3></div><span className="status-dot">Ổn định</span></div><div className="health-row"><span>API & xác thực</span><strong>Operational</strong></div><div className="health-row"><span>Database</span><strong>Operational</strong></div></article><article className="admin-panel accent-panel motion-in" style={{ "--motion-delay": "350ms" }}><span className="eyebrow">QUICK ACTION</span><h3>Giữ cho marketplace luôn an toàn.</h3><p>Kiểm tra báo cáo và duyệt những tin tuyển dụng đang chờ xử lý.</p><Link to="/admin/reports">Mở hàng đợi kiểm duyệt <i className="bi bi-arrow-right" /></Link></article></div></section>;
}
